from dataclasses import dataclass


@dataclass(frozen=True)
class VibeProfile:
    name: str                    # canonical lowercase (e.g. "action", "sci-fi")
    temp_shift: float            # +warm/-cool applied to R and B channels
    saturation: float            # 1.0 = no change
    contrast: float              # 1.0 = no change, pivot at 0.5
    brightness: float            # uniform offset
    lufs_target: float           # integrated loudness target (negative)
    act1_avg_cut_s: float        # seconds per cut, Act 1
    act2_avg_cut_s: float        # seconds per cut, Act 2
    act3_avg_cut_s: float        # seconds per cut, Act 3
    clip_count_min: int
    clip_count_max: int
    dialogue_ratio: float        # 0.0 = all visual; 1.0 = all dialogue clips
    primary_transition: str      # "hard_cut" | "crossfade" | "fade_to_black"
    secondary_transition: str    # used at act boundaries
    lut_filename: str            # e.g. "action_teal_orange.cube"
    pacing_curve: str            # human description


# All 18 vibe profiles keyed by canonical lowercase name.
# Keys must exactly match the VALID_VIBES frozenset in schema.py.
VIBE_PROFILES: dict[str, VibeProfile] = {
    "action": VibeProfile(
        name="action",
        temp_shift=-0.05,
        saturation=1.15,
        contrast=1.20,
        brightness=0.00,
        lufs_target=-14.0,
        act1_avg_cut_s=4.0,
        act2_avg_cut_s=2.5,
        act3_avg_cut_s=1.2,
        clip_count_min=25,
        clip_count_max=35,
        dialogue_ratio=0.25,
        primary_transition="hard_cut",
        secondary_transition="hard_cut",
        lut_filename="action_teal_orange.cube",
        pacing_curve="moderate -> fast -> montage",
    ),
    "adventure": VibeProfile(
        name="adventure",
        temp_shift=0.03,
        saturation=1.10,
        contrast=1.10,
        brightness=0.02,
        lufs_target=-14.0,
        act1_avg_cut_s=5.0,
        act2_avg_cut_s=3.5,
        act3_avg_cut_s=2.0,
        clip_count_min=20,
        clip_count_max=30,
        dialogue_ratio=0.35,
        primary_transition="crossfade",
        secondary_transition="fade_to_black",
        lut_filename="adventure_warm.cube",
        pacing_curve="steady -> brisk -> swift",
    ),
    "animation": VibeProfile(
        name="animation",
        temp_shift=0.00,
        saturation=1.25,
        contrast=1.00,
        brightness=0.03,
        lufs_target=-16.0,
        act1_avg_cut_s=5.0,
        act2_avg_cut_s=3.5,
        act3_avg_cut_s=2.5,
        clip_count_min=18,
        clip_count_max=25,
        dialogue_ratio=0.40,
        primary_transition="hard_cut",
        secondary_transition="crossfade",
        lut_filename="animation_vivid.cube",
        pacing_curve="steady -> brisk -> punchy",
    ),
    "comedy": VibeProfile(
        name="comedy",
        temp_shift=0.05,
        saturation=1.10,
        contrast=0.90,
        brightness=0.03,
        lufs_target=-16.0,
        act1_avg_cut_s=5.0,
        act2_avg_cut_s=4.0,
        act3_avg_cut_s=3.0,
        clip_count_min=15,
        clip_count_max=22,
        dialogue_ratio=0.55,
        primary_transition="hard_cut",
        secondary_transition="crossfade",
        lut_filename="comedy_warm_soft.cube",
        pacing_curve="relaxed -> moderate -> lively",
    ),
    "crime": VibeProfile(
        name="crime",
        temp_shift=-0.05,
        saturation=0.75,
        contrast=1.25,
        brightness=-0.02,
        lufs_target=-18.0,
        act1_avg_cut_s=5.0,
        act2_avg_cut_s=3.5,
        act3_avg_cut_s=2.0,
        clip_count_min=20,
        clip_count_max=28,
        dialogue_ratio=0.40,
        primary_transition="hard_cut",
        secondary_transition="fade_to_black",
        lut_filename="crime_noir.cube",
        pacing_curve="measured -> taut -> sharp",
    ),
    "documentary": VibeProfile(
        name="documentary",
        temp_shift=0.00,
        saturation=0.90,
        contrast=1.00,
        brightness=0.00,
        lufs_target=-20.0,
        act1_avg_cut_s=7.0,
        act2_avg_cut_s=5.0,
        act3_avg_cut_s=4.0,
        clip_count_min=12,
        clip_count_max=18,
        dialogue_ratio=0.60,
        primary_transition="crossfade",
        secondary_transition="crossfade",
        lut_filename="documentary_neutral.cube",
        pacing_curve="slow -> steady -> deliberate",
    ),
    "drama": VibeProfile(
        name="drama",
        temp_shift=-0.02,
        saturation=0.85,
        contrast=1.15,
        brightness=-0.01,
        lufs_target=-18.0,
        act1_avg_cut_s=7.0,
        act2_avg_cut_s=5.0,
        act3_avg_cut_s=3.5,
        clip_count_min=14,
        clip_count_max=20,
        dialogue_ratio=0.55,
        primary_transition="crossfade",
        secondary_transition="fade_to_black",
        lut_filename="drama_intimate.cube",
        pacing_curve="slow -> steady -> purposeful",
    ),
    "family": VibeProfile(
        name="family",
        temp_shift=0.05,
        saturation=1.10,
        contrast=0.90,
        brightness=0.03,
        lufs_target=-16.0,
        act1_avg_cut_s=5.0,
        act2_avg_cut_s=4.0,
        act3_avg_cut_s=3.0,
        clip_count_min=16,
        clip_count_max=22,
        dialogue_ratio=0.45,
        primary_transition="crossfade",
        secondary_transition="crossfade",
        lut_filename="family_warm.cube",
        pacing_curve="relaxed -> moderate -> lively",
    ),
    "fantasy": VibeProfile(
        name="fantasy",
        temp_shift=0.00,
        saturation=1.15,
        contrast=1.10,
        brightness=0.02,
        lufs_target=-16.0,
        act1_avg_cut_s=6.0,
        act2_avg_cut_s=4.0,
        act3_avg_cut_s=2.5,
        clip_count_min=18,
        clip_count_max=26,
        dialogue_ratio=0.35,
        primary_transition="crossfade",
        secondary_transition="fade_to_black",
        lut_filename="fantasy_rich.cube",
        pacing_curve="measured -> brisk -> swift",
    ),
    "history": VibeProfile(
        name="history",
        temp_shift=0.07,
        saturation=0.80,
        contrast=1.15,
        brightness=-0.02,
        lufs_target=-18.0,
        act1_avg_cut_s=7.0,
        act2_avg_cut_s=5.0,
        act3_avg_cut_s=3.5,
        clip_count_min=14,
        clip_count_max=20,
        dialogue_ratio=0.55,
        primary_transition="crossfade",
        secondary_transition="fade_to_black",
        lut_filename="history_sepia.cube",
        pacing_curve="slow -> steady -> purposeful",
    ),
    "horror": VibeProfile(
        name="horror",
        temp_shift=-0.03,
        saturation=0.70,
        contrast=1.35,
        brightness=-0.05,
        lufs_target=-20.0,
        act1_avg_cut_s=6.0,
        act2_avg_cut_s=4.0,
        act3_avg_cut_s=1.8,
        clip_count_min=20,
        clip_count_max=28,
        dialogue_ratio=0.30,
        primary_transition="hard_cut",
        secondary_transition="fade_to_black",
        lut_filename="horror_dark.cube",
        pacing_curve="tense -> jarring -> barrage",
    ),
    "music": VibeProfile(
        name="music",
        temp_shift=0.00,
        saturation=1.20,
        contrast=0.95,
        brightness=0.02,
        lufs_target=-14.0,
        act1_avg_cut_s=4.0,
        act2_avg_cut_s=3.0,
        act3_avg_cut_s=2.0,
        clip_count_min=20,
        clip_count_max=28,
        dialogue_ratio=0.20,
        primary_transition="hard_cut",
        secondary_transition="hard_cut",
        lut_filename="music_vivid.cube",
        pacing_curve="brisk -> fast -> montage",
    ),
    "mystery": VibeProfile(
        name="mystery",
        temp_shift=-0.04,
        saturation=0.75,
        contrast=1.20,
        brightness=-0.03,
        lufs_target=-18.0,
        act1_avg_cut_s=6.0,
        act2_avg_cut_s=4.5,
        act3_avg_cut_s=3.0,
        clip_count_min=16,
        clip_count_max=22,
        dialogue_ratio=0.45,
        primary_transition="crossfade",
        secondary_transition="fade_to_black",
        lut_filename="mystery_muted.cube",
        pacing_curve="measured -> taut -> deliberate",
    ),
    "romance": VibeProfile(
        name="romance",
        temp_shift=0.07,
        saturation=1.05,
        contrast=0.85,
        brightness=0.04,
        lufs_target=-18.0,
        act1_avg_cut_s=7.0,
        act2_avg_cut_s=5.0,
        act3_avg_cut_s=4.0,
        clip_count_min=12,
        clip_count_max=18,
        dialogue_ratio=0.55,
        primary_transition="crossfade",
        secondary_transition="fade_to_black",
        lut_filename="romance_warm.cube",
        pacing_curve="slow -> steady -> tender",
    ),
    "sci-fi": VibeProfile(
        name="sci-fi",
        temp_shift=-0.08,
        saturation=0.90,
        contrast=1.25,
        brightness=-0.02,
        lufs_target=-14.0,
        act1_avg_cut_s=5.0,
        act2_avg_cut_s=3.5,
        act3_avg_cut_s=2.0,
        clip_count_min=22,
        clip_count_max=30,
        dialogue_ratio=0.35,
        primary_transition="hard_cut",
        secondary_transition="fade_to_black",
        lut_filename="scifi_cold.cube",
        pacing_curve="measured -> brisk -> rapid",
    ),
    "thriller": VibeProfile(
        name="thriller",
        temp_shift=-0.04,
        saturation=0.85,
        contrast=1.30,
        brightness=-0.03,
        lufs_target=-16.0,
        act1_avg_cut_s=5.0,
        act2_avg_cut_s=3.0,
        act3_avg_cut_s=1.5,
        clip_count_min=25,
        clip_count_max=35,
        dialogue_ratio=0.30,
        primary_transition="hard_cut",
        secondary_transition="fade_to_black",
        lut_filename="thriller_tense.cube",
        pacing_curve="taut -> fast -> barrage",
    ),
    "war": VibeProfile(
        name="war",
        temp_shift=-0.02,
        saturation=0.70,
        contrast=1.20,
        brightness=-0.03,
        lufs_target=-16.0,
        act1_avg_cut_s=5.0,
        act2_avg_cut_s=3.0,
        act3_avg_cut_s=1.5,
        clip_count_min=25,
        clip_count_max=35,
        dialogue_ratio=0.25,
        primary_transition="hard_cut",
        secondary_transition="hard_cut",
        lut_filename="war_desaturated.cube",
        pacing_curve="heavy -> fast -> assault",
    ),
    "western": VibeProfile(
        name="western",
        temp_shift=0.08,
        saturation=0.85,
        contrast=1.15,
        brightness=-0.01,
        lufs_target=-18.0,
        act1_avg_cut_s=6.0,
        act2_avg_cut_s=4.5,
        act3_avg_cut_s=3.0,
        clip_count_min=16,
        clip_count_max=22,
        dialogue_ratio=0.45,
        primary_transition="crossfade",
        secondary_transition="fade_to_black",
        lut_filename="western_amber.cube",
        pacing_curve="steady -> measured -> purposeful",
    ),
}
